trailingComma: es5
tabWidth: 2
semi: true
singleQuote: true
plugins:
  - '@trivago/prettier-plugin-sort-imports'
  - 'prettier-plugin-svelte'
  - 'prettier-plugin-tailwindcss'
importOrderParserPlugins:
  - 'typescript'
  - 'decorators-legacy'
importOrder:
  - <THIRD_PARTY_MODULES>
  - '^\./(.*)$'
  - '^\.\./(.*)$'
importOrderSeparation: true
importOrderSortSpecifiers: true
tailwindStylesheet: ./src/app.css
tailwindPreserveWhitespace: false
overrides:
  - files: '*.svelte'
    options:
      parser: svelte
